export const LocalStorageLocations = {
  USER_ID: 'USER_ACCOUNT_UID',
  USER_SURVEY_FINISHED: 'USER_SURVEY_FINISHED',
  USER_ACCOUNT_INFO: 'USER_ACCOUNT_INFO',
  FCM_TOKEN: 'FCM_TOKEN',
  APP_CONFIG: 'APP_CONFIG',
  IP_ADDRESS: 'IP_ADDRESS',
};
